config/routes.rb
Saveohno::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  match '/failure', to: 'pre_launch_users#signup_failure', via: :get
  match '/success', to: 'pre_launch_users#signup_success', via: :get
  match '/donate',  to: 'static_pages#donate',             via: :get

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pre_launch_user.rb
class PreLaunchUser < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
	validates :donation_amount, presence: true
	validates :pledged, inclusion: [true]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pre_launch_users_controller.rb
class PreLaunchUsersController < ApplicationController
  def new
    @pre_launch_user = PreLaunchUser.new
    render :layout => false
  end

  def pledge
    @pre_launch_user = PreLaunchUser.new
    render :layout => false
  end

  def signup_failure
  	@pre_launch_user = PreLaunchUser.new
  	render :layout => false
  end

  def signup_success
  	render :layout => false
  end

  def create
	@pre_launch_user = PreLaunchUser.new(pre_launch_user_params)
	if @pre_launch_user.save 
	  redirect_to success_path
	else
	  redirect_to failure_path
	end
  end

	private
	  def pre_launch_user_params
	  	params.require(:pre_launch_user).permit(:name, :email, :donation_amount, :pledged)
	  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
	@pre_launch_user = PreLaunchUser.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pre_launch_users_helper.rb
module PreLaunchUsersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to image_tag('logo.png', class: 'logo'), root_path %>
  <nav>
    <ul class="nav pull-right">
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saveohno</title>
  <%= stylesheet_link_tag "laptop", media: "screen and (min-width: 1450px)", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "laptop2", media: "screen and (min-width: 1305px) and (max-width: 1450px)", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "laptop3", media: "screen and (min-width: 1100px) and (max-width: 1305px)", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "laptop4", media: "screen and (min-width: 950px) and (max-width: 1100px)", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "tablet", media: "screen and (min-width: 750px) and (max-width: 950px)", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "tablet", media: "screen and (max-width: 750px)", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script src="//fast.eager.io/_DQRpBK4qp.js"></script>
</head>
<body>
<header>
	<div class="logo-wrapper">
    	<span class="helper"></span>
      <%= image_tag 'logo.png', class: 'logo' %>
    </div>
    <p class="points"> Points: 0 </p>
</header>

<%= yield %>

</body>
</html>

app/views/pre_launch_users/_mailing_list_request.html.erb
<p> SaveOhno.org is coming soon.<br> Wanna stay updated on our progress<br> towards launch and gain some<br> early-bird points? Sign up now!</p>
<div id="new-user-form">
<%= form_for(@pre_launch_user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "Submit", class: "submit-button" %>
<% end %>
</div>
<p>(we won't spam you, we promise)</p>

app/views/pre_launch_users/_new_pre_launch_user.html.erb
<p> SaveOhno.org is coming soon.<br> Wanna stay updated on our progress<br> towards launch and gain some<br> early-bird points? Sign up now!</p>
<div id="new-user-form">
<%= form_for(@pre_launch_user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "Submit", class: "submit-button" %>
<% end %>
</div>
<p>(we won't spam you, we promise)</p>

app/views/pre_launch_users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveOhno | Kickstarter Pledge</title>
  <%= stylesheet_link_tag "pre_launch_users", media: "screen", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <!-- <div class="overlay2">
      <div class="floating-wrapper">
        <div class="floating-window">
          <div class="select-question">
            <h2> Do you want to select this perk? </h2>
            <div class="button-yes">Yes</div>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <div class="button-no">No</div>
          </div>  
          <div class="new-user-form">
            <h4>You're the best! Please fill out the following info and we'll email you when we launch our Kickstarter campaign.</h4>
            <%= form_for(@pre_launch_user) do |f| %>
              <%= f.label :name %>
              <%= f.text_field :name %>

              <%= f.label :donation_amount %>
              <%= f.text_field :donation_amount %>
              <br>
              <%= f.check_box :pledged %>
              <%= f.label :pledged, "The Pledge", class: "checkbox inline" %>
              <p> I pledge to pay this amount to SaveOhno.org's Kickstarter campaign once it launches and I'm emailed a reminder. </p>

              <%= f.label :email %>
              <%= f.text_field :email %>
              <br>
              (Don't worry, we won't spam you. We promise.)

              <br>  
              <%= f.submit "Submit", class: "submit-button" %>
              &nbsp;&nbsp;&nbsp;&nbsp;
              <div class="button-no button-close">Close</div>
            <% end %>
          </div>  
        </div>
      </div>
    </div>
    -->
    <h1> Help us with our upcoming Kickstarter campaign! </h1>
    <h3> Our campaign will be launching on November 29th, and we're looking to collect 30% in pledges before we even launch. Help us rise to the top of Kickstarter's listings by <span class="bold">pledging to donate</span> on day 1! </h3>
    <br>
    <%= link_to 'Learn more about SaveOhno', root_path %>
  <%= link_to(pledge_path) do %>
    <div class="not-perk">
      <h3> <$10 </h3>
      <div class="ul-wrapper">
        <ul>
          <li> Our eternal gratitude. </li>
        </ul>
      </div>  
    </div>
    <div class="perk perk-small margin-right">
      <h3> Perk #1: $10-24.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Bronze 'Kickstarter' Badge on your SaveOhno Profile </li>
      </ul>
      <%= image_tag 'Perk Level 1.png', class: 'perk-1-img perk-img' %>
    </div>
    <div class="perk perk-small">
      <h3> Perk #2: $25-49.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Bronze 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
      </ul>
      <%= image_tag 'Perks Level 2.png', class: 'perk-2-img perk-img' %>
    </div>
    <div class="perk perk-med margin-right">
      <h3> Perk #3: $50-99.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Silver 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
        <li> Customized 'Ohno-style' picture of you </li>
        <li> Early access beta tester </li>
      </ul>
      <%= image_tag 'Perks Level 3.png', class: 'perk-3-img perk-img' %>
    </div>
    <div class="perk perk-med">
      <h3> Perk #4: $100-149.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Silver 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
        <li> Customized 'Ohno-style' picture of you </li>
        <li> Early access beta tester </li>
        <li> We plant a tree </li>
      </ul>
      <%= image_tag 'Perks level 4.png', class: 'perk-4-img perk-img' %>
    </div>
    <div class="perk perk-big margin-right">
      <h3> Perk #5: $150-199.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Gold 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
        <li> Customized 'Ohno-style' picture of you </li>
        <li> Early access beta tester </li>
        <li> Warning: Climate Change Coming T-Shirt </li>
      </ul>
      <%= image_tag 'Perks level 5.png', class: 'perk-5-img perk-img' %>
  </div>
  <div class="perk perk-big">
      <h3> Perk #6: $200-499.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Gold 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
        <li> Customized 'Ohno-style' picture of you </li>
        <li> Early access beta tester </li>
        <li> 'The Lump Of Coal': Glass box with a piece of coal inside, engraved with: "One less piece of coal for the atmosphere"  </li>
      </ul>
      <%= image_tag 'Perks level 6.png', class: 'perk-6-img perk-img' %>
  </div>
  <div class="perk perk-huge margin-right">
      <h3> Perk #7: $500-999.99 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Platinum 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
        <li> Customized 'Ohno-style' picture of you </li>
        <li> Early access beta tester </li>
        <li> Warning: Climate Change Coming T-Shirt </li>
        <li> 'The Lump Of Coal': Glass box with a piece of coal inside, engraved with: "One less piece of coal for the atmosphere"  </li>
        <li> Your 'Ohno-style' character will be in the actual Ohno game </li>
      </ul>
      <%= image_tag 'Perks level 7.png', class: 'perk-7-img perk-img' %>
   </div>
    <div class="perk perk-huge">
      <h3> Perk #8: $1000 </h3>
      <ul>
        <li> Thank you email </li>
        <li> Platinum 'Kickstarter' Badge on your SaveOhno Profile </li>
        <li> Your name feauted on our website </li>
        <li> Custom SaveOhno pen </li>
        <li> Customized 'Ohno-style' picture of you </li>
        <li> Early access beta tester </li>
        <li> Warning: Climate Change Coming T-Shirt </li>
        <li> 'The Lump Of Coal': Glass box with a piece of coal inside, engraved with: "One less piece of coal for the atmosphere"  </li>
        <li> Your 'Ohno-style' character will be in the actual Ohno game </li>
        <li> Board position interview </li>
      </ul>
      <%= image_tag 'Perks Level 8.png', class: 'perk-8-img perk-img' %>
   </div>
   <div class="not-perk">
      <h3> >$1000 </h3>
      <div class="ul-wrapper">
        <ul>
          <li> We'll contact you to discuss sponsorship opportunities. </li>
        </ul>
      </div>  
    </div>
  <% end %>  
    <footer class="footer">
    <small>
      SaveOhno.org is a nonprofit<br> corporation in the state of MA
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   root_path %></li>
      </ul>
    </nav>
  </footer>
</body>
</html>

app/views/pre_launch_users/pledge.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveOhno | Kickstarter Pledge Form</title>
  <%= stylesheet_link_tag "pre_launch_users", media: "screen", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <h1> You're the best! Please fill in all the fields and check 'The Pledge' </h1>
    <center><div id="new-user-form-after">
    <%= form_for(@pre_launch_user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :donation_amount %>
      <%= f.text_field :donation_amount %>
      <br>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <br>
      (Don't worry, we won't spam you. We promise.)
      <br>
      <br>
      <%= f.check_box :pledged %>
      <%= f.label :pledged, "The Pledge", class: "checkbox inline" %>
      <p> I pledge to pay this amount to SaveOhno.org's Kickstarter campaign once it launches and I'm emailed a reminder. </p>
      <br>
      <br>
      <%= f.submit "Submit", class: "submit-button" %>
    <% end %>
    </div>
    <br>
    <br>
    <%= link_to 'Go back', new_pre_launch_user_path %>
    </center>
  </div>  
</body>
</html>  

app/views/pre_launch_users/signup_failure.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveOhno | Kickstarter Pledge</title>
  <%= stylesheet_link_tag "pre_launch_users", media: "screen", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <h1> Sign up failed, please fill in all fields and check 'The Pledge' </h1>
    <center><div id="new-user-form-after">
    <%= form_for(@pre_launch_user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :donation_amount %>
      <br>
      <%= f.text_field :donation_amount %>
      <br>

      <%= f.check_box :pledged %>
      <%= f.label :pledged, "The Pledge", class: "checkbox inline" %>
      <p> I pledge to pay this amount to SaveOhno.org's Kickstarter campaign once it launches and I'm emailed a reminder. </p>
      <br>

      <%= f.label :email %>
      <%= f.text_field :email %>
      <br>
      <br>
      <%= f.submit "Submit", class: "submit-button" %>
    <% end %>
    </div>
    <br>
    <br>
    <%= link_to 'Go back', new_pre_launch_user_path %>
    </center>
  </div>  
</body>
</html>  

app/views/pre_launch_users/signup_success.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveOhno | Kickstarter Pledge</title>
  <%= stylesheet_link_tag "pre_launch_users", media: "screen", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "c930d368-d906-4262-b627-352cc4fedd1f", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
	<h1> Thank you! </h1>
	<br>
	<br>
	<center>
	<h3> Multiply Your Impact </h3>
	<span class='st_facebook_large' displayText='Facebook'></span>
	<span class='st_twitter_large' displayText='Tweet'></span>
	<span class='st_linkedin_large' displayText='LinkedIn'></span>
	<span class='st_email_large' displayText='Email'></span>
	<br>
	<%= link_to 'Learn more about SaveOhno', root_path %>
	</center>
  </div>
</body>
</html>

app/views/static_pages/donate.html.erb
<!DOCTYPE html>  
<html>
<head>
  <title>SaveOhno</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="floating-display">
    <%= image_tag 'floating-display2.png', class: 'floating-display-img' %>
  <!-- Begin PayPal button -->
  <div class="logo-wrapper"><div class="paypal-button">
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="VDJCPFEHWM23N">
      <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="  PayPal - The safer, easier way to pay online!">
      <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
   </div></div>
  <!-- End PayPal button -->
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>  
<html>
<head>
  <title>SaveOhno</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="turn-device">
    <p> On a phone or tablet? Please turn your device sideways! </p>
    <p> On a laptop or desktop? Please make your browser window larger! </p>
  </div>
  <div class="hub">
    <%= image_tag 'hub2.png', id: 'hub-start' %>
    <%= image_tag 'fingerprint.png', id: 'fingerprint' %> 
    <%= image_tag 'fingerprint2.png', id: 'fingerprint2' %> 
    <%= image_tag 'access-granted.png', id: 'access-granted' %>
    <%= image_tag 'who-is-ohno2.png', id: 'who-is-ohno' %>
    <%= image_tag 'what-is-saveohno2.png', id: 'what-is-saveohno' %>
    <%= image_tag 'stay-updated2.png', id: 'stay-updated' %>
  </div>
  <%= image_tag 'arrow.png', id: 'start-here' %>
  <div class="overlay"></div>
  <div class="floating-display">
    <%= image_tag 'floating-display2.png', class: 'floating-display-img' %>
    <div class="who-is-ohno-content">
      <p id="who-is-ohno-line1">This is your great <br>granddaughter, Ohno.</p>
      <p id="who-is-ohno-line2">She lives far in the<br> future, in a time seriously<br> affected by the climate<br> change caused from today<br></p>
      <%= image_tag 'OHNO-sad.png', class: 'ohno-sad' %>
      <br>
      <div class="ohno-wrapper">
        <%= image_tag 'OHNO.png', class: 'ohno' %>
      </div>
    </div>
    <div class="what-is-saveohno-content">
      <p id="what-is-saveohno-line1">SaveOhno.org is a platform <br> (launching soon) where people can<br> see climate change affect the <br>life of Ohno.<br></p>
      <%= image_tag 'ohno-tornado.png', class: 'ohno-tornado' %> 
      <p id="what-is-saveohno-line2">Through this site, users'<br> real world actions influence the<br> virtual life of Ohno. If a user<br> signs petitions, emails politicians,<br> supports projects etc, Ohno's life<br> improves. If the user doesn't,<br> her life only worsens.</p>
      <p id="what-is-saveohno-line3">This is your world, and <br>you determine its level of<br> prosperity, or despair.<br></p>
      <%= image_tag 'OHNO-neutral.png', class: 'ohno-neutral' %>
    </div>
    <div class="next-button-wrapper">
      <%= image_tag 'Next Button.png', id: 'next-button' %>
    </div>
    <div class="stay-updated-content">
      <p> SaveOhno.org is coming soon. <br>Wanna stay updated on our progress <br>towards launch, gain some early bird <br>points,and help us get funded? </p>
      <br><br>
      <!-- Begin PayPal button -->
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="VDJCPFEHWM23N">
        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="  PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
      </form>
      <!-- End PayPal button -->
    </div>
  </div> 
  <a href="https://www.kickstarter.com/projects/136597581/saveohnoorg">
    <%= image_tag('kickstarter-badge-beveled.png', class: 'kickstarter-badge') %>
  </a>  
</body>
</html>